import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/quiz_model.dart';

class QuizService {
  static const String apiUrl = 'https://api.jsonserve.com/Uw5CrX';

  Future<Autogenerated> fetchQuiz() async {
    try {
      final response = await http.get(Uri.parse(apiUrl));

      if (response.statusCode == 200) {
        final jsonData = json.decode(response.body);
        return Autogenerated.fromJson(jsonData);
      } else {
        throw Exception('Failed to load quiz');
      }
    } catch (e) {
      throw Exception('Error fetching quiz: $e');
    }
  }
}
